export const FEEDBACK_MATRIX: Record<string, Record<string, string>> = {
  'ow': {
    'pv': "Kijk welk woord verandert als je de tijd aanpast.",
    'lv': "Dit deel doet iets — maar welk deel ondergaat de handeling?",
    'mv': "Dit deel doet iets — maar wie ontvangt er iets in de zin?",
    'bwb': "Geeft dit deel extra info, of is het een woord als 'niet', 'wel' of 'ook'?",
    'wg': "Bestaat dit deel uit werkwoorden die een actie beschrijven?",
    'ng': "Zegt dit gezegde wat het onderwerp is of wordt?",
    'vv': "Hoort het voorzetsel vast bij een ander woord in de zin?",
    'bijzin': "Heeft dit deel een eigen onderwerp en persoonsvorm?",
    'bijst': "Geeft dit deel een extra naam aan iets wat al eerder genoemd is?",
  },

  'pv': {
    'wg': "Het WG zijn alle werkwoorden die samen de handeling uitdrukken.",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'lv': "Dit is een werkwoord — welk deel ondergaat de handeling?",
    'bwb': "Geeft dit deel extra info, of is het een woord als 'niet' of 'ook'?",
    'ng': "Zegt dit gezegde wat het onderwerp is of wordt?",
    'mv': "Dit is een werkwoord — welk deel ontvangt er iets?",
    'vv': "Hoort het voorzetsel vast bij een specifiek woord in de zin?",
  },

  'wg': {
    'pv': "Kijk welk woord van vorm verandert als je de tijd aanpast.",
    'ng': "Drukken deze woorden een actie uit, of zeggen ze wat het onderwerp is of wordt?",
    'lv': "Dit zijn de werkwoorden — welk deel ondergaat de handeling?",
    'bwb': "Geeft dit deel extra info, of is het een woord als 'niet' of 'ook'?",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'mv': "Dit zijn de werkwoorden — welk deel ontvangt er iets?",
    'vv': "Hoort het voorzetsel vast bij een specifiek woord in de zin?",
    'wwd': "Het WWD hoort bij een naamwoordelijk gezegde, niet bij een werkwoordelijk.",
  },

  'ng': {
    'wg': "Drukken deze werkwoorden een actie uit, of beschrijven ze een eigenschap?",
    'lv': "Dit zegt wat het OW is — welk deel ondergaat de handeling?",
    'bwb': "Geeft dit deel extra info, of is het een woord als 'niet' of 'wel'?",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'pv': "Kijk welk werkwoord verandert als je de tijd aanpast.",
    'mv': "Dit zegt wat het OW is — welk deel ontvangt er iets?",
    'vv': "Hoort het voorzetsel vast bij een specifiek woord in de zin?",
    'wwd': "Zoek het woord dat zegt wát het onderwerp is of wordt.",
  },

  'lv': {
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'vv': "Hoort het voorzetsel onlosmakelijk bij een woord in de zin?",
    'bwb': "Dit deel ondergaat niets — geeft het extra info over de omstandigheid?",
    'mv': "Ontvangt dit deel iets, of ondergaat het iets?",
    'ng': "Dit deel ondergaat iets — zegt het ook wat het OW is of wordt?",
    'bijst': "Geeft dit deel een extra naam aan een woord dat al genoemd is?",
    'pv': "Kijk welk woord verandert bij de tijdproef.",
    'wg': "Dit deel ondergaat niets — dit zijn de werkwoorden die de handeling uitdrukken.",
    'bijzin': "Heeft dit deel intern een eigen onderwerp en persoonsvorm?",
  },

  'mv': {
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'lv': "Ontvangt dit deel iets, of ondergaat het iets?",
    'vv': "Dit deel is geen ontvanger — het hangt via een vast voorzetsel aan een ander woord.",
    'bwb': "Dit deel ontvangt niets — geeft het extra info over de omstandigheid?",
    'pv': "Kijk welk woord verandert als je de tijd aanpast.",
    'wg': "Dit deel ontvangt niets — dit zijn de werkwoorden die de handeling uitdrukken.",
    'ng': "Dit deel ontvangt niets — zegt het wat het OW is of wordt?",
    'bijzin': "Heeft dit deel intern een eigen onderwerp en persoonsvorm?",
  },

  'vv': {
    'bwb': "Duidt het voorzetsel een plaats of tijd aan, of hoort het vast bij een specifiek woord?",
    'lv': "Dit hangt vast aan een ander woord — welk deel ondergaat de handeling?",
    'mv': "Dit hangt vast aan een ander woord — welk deel ontvangt er iets?",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'pv': "Kijk welk werkwoord verandert bij de tijdproef.",
    'wg': "Het WG zijn werkwoorden die een handeling uitdrukken — dit deel begint met een voorzetsel.",
    'ng': "Zegt dit deel wat het onderwerp is of wordt?",
    'bijzin': "Heeft dit deel intern een eigen onderwerp en persoonsvorm?",
  },

  'bwb': {
    'vv': "Hoort het voorzetsel onlosmakelijk bij een specifiek woord in de zin?",
    'lv': "Dit geeft extra info — welk deel ondergaat de handeling?",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'bijzin': "Heeft dit deel een eigen onderwerp en persoonsvorm?",
    'mv': "Dit geeft extra info — welk deel ontvangt er iets?",
    'ng': "Zegt dit gezegde wat het onderwerp is of wordt?",
    'bijst': "Geeft dit deel een extra naam aan een zinsdeel dat er direct voor staat?",
    'pv': "Kijk welk woord verandert als je de tijd aanpast.",
    'wg': "Bestaat dit deel uit werkwoorden die een handeling beschrijven?",
  },

  'bijst': {
    'bijv_bep': "Zegt dit alleen iets over één woord, of hernoemt het een heel zinsdeel?",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'lv': "Dit is een extra naam — welk deel ondergaat de handeling?",
    'bwb': "Geeft dit deel info over de omstandigheden, of is het een woord als 'niet' of 'ook'?",
    'pv': "Kijk welk woord van vorm verandert bij de tijdproef.",
    'mv': "Dit is een extra naam — wie ontvangt er iets in de zin?",
    'vv': "Kijk of het voorzetsel onlosmakelijk bij een woord in de zin hoort.",
    'bijzin': "Heeft dit deel intern een eigen onderwerp en persoonsvorm?",
  },

  'bijzin': {
    'bwb': "Heeft dit deel een eigen onderwerp én persoonsvorm, of is het extra info?",
    'ow': "Heeft dit deel een eigen onderwerp én persoonsvorm?",
    'lv': "Dit deel heeft geen eigen persoonsvorm — welk deel ondergaat de handeling?",
    'mv': "Dit deel heeft geen eigen persoonsvorm — welk deel ontvangt er iets?",
    'vv': "Hoort het voorzetsel vast bij een specifiek woord — heeft dit deel echt een eigen PV?",
    'pv': "Kijk welk enkel woord van vorm verandert bij de tijdproef.",
    'wg': "Bestaat dit deel uit de werkwoorden van de zin die een actie beschrijven?",
  },

  'vw_onder': {
    'vw_neven': "Verbindt dit twee gelijke zinnen, of maakt het één deel afhankelijk?",
    'bwb': "Is dit een verbindingswoord, of een woord dat info geeft over tijd of plaats?",
    'pv': "Kijk welk woord van vorm verandert als je de tijd aanpast.",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'lv': "Dit is een verbindingswoord — welk deel ondergaat de handeling?",
    'mv': "Dit is een verbindingswoord — welk deel ontvangt er iets?",
    'wg': "Het WG zijn werkwoorden — dit woord verbindt een bijzin, het is zelf geen werkwoord.",
    'ng': "Zegt dit gezegde wat het onderwerp is of wordt?",
    'bijzin': "Kies je hier één woord of de volledige zin die volgt?",
  },

  'vw_neven': {
    'vw_onder': "Leidt dit een bijzin in, of verbindt het twee gelijke hoofdzinnen?",
    'bwb': "Is dit een verbindingswoord, of een woord dat info geeft over tijd of plaats?",
    'pv': "Kijk welk woord van vorm verandert als je de tijd aanpast.",
    'ow': "Denk na over wie of wat er in deze zin iets doet of is.",
    'lv': "Dit is een verbindingswoord — welk deel ondergaat de handeling?",
    'mv': "Dit is een verbindingswoord — welk deel ontvangt er iets?",
    'wg': "Hoort dit woord bij de werkwoorden die de handeling vormen?",
    'ng': "Zegt dit gezegde wat het onderwerp is of wordt?",
    'bijzin': "Kies je hier alleen het verbindingswoord of de hele bijzin?",
  },
};
